version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,sqs,dynamodb
      - DEBUG=1
    volumes:
      - "./localstack-data:/tmp/localstack"
